---
version: "2.1"
services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:10.10.3ubu2404-ls44
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - JELLYFIN_PublishedServerUrl=localhost
    volumes:
      - /etc/jellyfin/config:/config
      - /etc/jellyfin/cache:/cache
      - /etc/jellyfin/media/shows:/data/shows
      - /etc/jellyfin/media/movies:/data/movies
      - /etc/jellyfin/media/music:/data/music
    ports:
      - 8096:8096
      - 8920:8920 #optional
      - 7359:7359/udp #optional
      - 1900:1900/udp #optional
    restart: unless-stopped
